---
- name: add user 'webmaster'
  user: name='webmaster'

- name: add nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key

- name: add nginx repos
  apt_repository: repo='{{item}}'
  with_items:
    - 'deb http://nginx.org/packages/ubuntu/ precise nginx'
    - 'deb-src http://nginx.org/packages/ubuntu/ precise nginx'

- name: Install nginx
  apt: name=nginx state=present

- name: Make sure that the logs directory exsists
  action: file path=/home/webmaster/logs state=directory

- name: Copy nginx configuration for catch-all
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - {src: 'nginx.conf', dest: '/etc/nginx/nginx.conf'}
    - {src: 'default-site.conf', dest: '/etc/nginx/sites-available/default'}
  notify: restart nginx
