---
- name: add user 'webmaster'
  user: name='webmaster'

- name: add nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key

- name: add nginx repos
  apt_repository: repo=`deb http://nginx.org/packages/ubuntu/ precise nginx`
  apt_repository: repo=`deb-src http://nginx.org/packages/ubuntu/ precise nginx`

- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for catch-all
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  template: src=default-site.conf dest=/etc/nginx/site-available/default
  notify: restart nginx
