---
- name: Add PHP 5.5 repository
  apt_repository: repo='ppa:ondrej/php5'

- name: Install php-fpm and deps 
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-fpm
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-memcache
    - php-apc
    - php-pear
- name: Configure PHP
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf section=www option=listen value='127.0.0.1:9000' backup=yes
  notify: restart php-fpm
