---
- name: Install php-fpm and deps 
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-fpm
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-memcache
    - php-apc
  notify: restart php-fpm
