---
- name: add mariadb repos
  apt_repository: repo='deb http://mirrors.supportex.net/mariadb/repo/5.5/ubuntu precise main'

- name: Addkey Mariadb
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db

- name: install mariadb
  apt: name=mariadb-server state=latest update_cache=yes