---
- name: add mariadb repos
  apt_repository: repo='deb http://ams2.mirrors.digitalocean.com/mariadb/repo/5.5/ubuntu trusty main'

- name: Addkey Mariadb
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db

- name: install mariadb
  apt: name=mariadb-server state=latest update_cache=yes