---
- name: installing basic soft
  apt: pkg=$item
  with_items:
    - mc
    - htop
    - iftop
    - curl

- name: installing screen with config file
  apt: pkg=screen

- name: install screen config file
  copy: src=.screenrc dest=/root/.screenrc
